// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PROJECT_68_BE.Models;

namespace PROJECT_68_BE.Migrations
{
    [DbContext(typeof(Anime68Context))]
    [Migration("20201015185830_InitialDB")]
    partial class InitialDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PROJECT_68_BE.Models.AirDate", b =>
                {
                    b.Property<int>("AirDateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Air_Date_ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AirDateName")
                        .HasColumnName("Air_Date_Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("AirDateId");

                    b.ToTable("Air_Date");
                });

            modelBuilder.Entity("PROJECT_68_BE.Models.AnimeType", b =>
                {
                    b.Property<int>("AnimeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Anime_Type_ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AnimeTypeDescription")
                        .HasColumnName("Anime_Type_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnimeTypeName")
                        .IsRequired()
                        .HasColumnName("Anime_Type_Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("AnimeTypeId");

                    b.ToTable("Anime_Type");
                });

            modelBuilder.Entity("PROJECT_68_BE.Models.Animes", b =>
                {
                    b.Property<int>("AnimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Anime_ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AirDateId")
                        .HasColumnName("Air_Date_ID")
                        .HasColumnType("int");

                    b.Property<string>("AnimeImg")
                        .HasColumnName("Anime_Img")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("AnimeName")
                        .IsRequired()
                        .HasColumnName("Anime_Name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("AnimeSource")
                        .HasColumnName("Anime_Source")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<int>("AnimeTypeId")
                        .HasColumnName("Anime_Type_ID")
                        .HasColumnType("int");

                    b.Property<int?>("CommentId")
                        .HasColumnName("Comment_ID")
                        .HasColumnType("int");

                    b.Property<int?>("EpsodesTotal")
                        .HasColumnName("Epsodes_Total")
                        .HasColumnType("int");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.Property<int?>("StudioId")
                        .HasColumnName("Studio_ID")
                        .HasColumnType("int");

                    b.Property<int?>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("AnimeId");

                    b.HasIndex("AnimeTypeId");

                    b.HasIndex("CommentId");

                    b.HasIndex("StudioId");

                    b.ToTable("Animes");
                });

            modelBuilder.Entity("PROJECT_68_BE.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Comment_ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CmtDate")
                        .HasColumnName("Cmt_Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ViewerId")
                        .HasColumnName("Viewer_ID")
                        .HasColumnType("int");

                    b.HasKey("CommentId");

                    b.HasIndex("ViewerId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("PROJECT_68_BE.Models.News", b =>
                {
                    b.Property<int>("NewsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("News_ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NewContent")
                        .HasColumnName("New_Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewName")
                        .HasColumnName("New_Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("NewsId");

                    b.ToTable("News");
                });

            modelBuilder.Entity("PROJECT_68_BE.Models.Studio", b =>
                {
                    b.Property<int>("StudioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Studio_ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StudioDescription")
                        .HasColumnName("Studio_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudioName")
                        .HasColumnName("Studio_Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("StudioId");

                    b.ToTable("Studio");
                });

            modelBuilder.Entity("PROJECT_68_BE.Models.Viewer", b =>
                {
                    b.Property<int>("ViewerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Viewer_ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ViewerEmail")
                        .IsRequired()
                        .HasColumnName("Viewer_Email")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("ViewerName")
                        .IsRequired()
                        .HasColumnName("Viewer_Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("ViewerPassword")
                        .IsRequired()
                        .HasColumnName("Viewer_Password")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("ViewerId");

                    b.ToTable("Viewer");
                });

            modelBuilder.Entity("PROJECT_68_BE.Models.Animes", b =>
                {
                    b.HasOne("PROJECT_68_BE.Models.AirDate", "AnimeType")
                        .WithMany("Animes")
                        .HasForeignKey("AnimeTypeId")
                        .HasConstraintName("FK_Animes_Air_Date")
                        .IsRequired();

                    b.HasOne("PROJECT_68_BE.Models.AnimeType", "AnimeTypeNavigation")
                        .WithMany("Animes")
                        .HasForeignKey("AnimeTypeId")
                        .HasConstraintName("FK_Animes_Anime_Type")
                        .IsRequired();

                    b.HasOne("PROJECT_68_BE.Models.Comment", "Comment")
                        .WithMany("Animes")
                        .HasForeignKey("CommentId")
                        .HasConstraintName("FK_Animes_Comment");

                    b.HasOne("PROJECT_68_BE.Models.Studio", "Studio")
                        .WithMany("Animes")
                        .HasForeignKey("StudioId")
                        .HasConstraintName("FK_Animes_Studio");
                });

            modelBuilder.Entity("PROJECT_68_BE.Models.Comment", b =>
                {
                    b.HasOne("PROJECT_68_BE.Models.Viewer", "Viewer")
                        .WithMany("Comment")
                        .HasForeignKey("ViewerId")
                        .HasConstraintName("FK_Comment_Viewer");
                });
#pragma warning restore 612, 618
        }
    }
}
